#!/usr/bin/python

import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument("-s", action="store_true", help="Silent")
parser.add_argument("-S", action="store_true", help="Show error")
parser.add_argument("-f", action="store_true", help="Fail")
parser.add_argument("-L", action="store_true", help="Location")
parser.add_argument("--netrc", action="store_true", help="Use .netrc file")
parser.add_argument("-o", help="Output file")
parser.add_argument("url", help="URL")
args = parser.parse_args()
output_file = open(args.o, "w")
output_file.write(" ".join(sys.argv[1:]))
