#!/usr/bin/env python

import sys

if len(sys.argv) == 2:
    if sys.argv[1] == "admin123":
        print '$shiro1$SHA-512$1024$OND5TXX1QaCgm3r1cWmMVQ==$UoNVW7ZEJ7VWmfBdjysXX1Ix9spFMJqZd4ldIVDfAXVhN66FW8mPer6IdvMH4V+3ZhifY8U3NJyQeoVjMHR0ag=='
        exit(0)

exit(1)
